export const ALL_CIRCUIT = 'ALL_CIRCUIT';
export const ALL_CIRCUIT_DETAILS = 'ALL_CIRCUIT_DETAILS';
export const ALL_CIRCUIT_SORT_BY_LOC_ID_ASC = 'ALL_CIRCUIT_SORT_BY_LOC_ID_ASC';
export const ALL_CIRCUIT_SORT_BY_LOC_ID_DES = 'ALL_CIRCUIT_SORT_BY_LOC_ID_DES';
export const ALL_CIRCUIT_SORT_BY_CIR_ID_ASC = 'ALL_CIRCUIT_SORT_BY_CIR_ID_ASC';
export const ALL_CIRCUIT_SORT_BY_CIR_ID_DES = 'ALL_CIRCUIT_SORT_BY_CIR_ID_DES';
export const ALL_CIRCUIT_SORT_BY_BRANCH_ASC =
  'ALL_CIRCUIT_SORT_BY_DEVICE_BRANCH_ASC';
export const ALL_CIRCUIT_SORT_BY_BRANCH_DES =
  'ALL_CIRCUIT_SORT_BY_DEVICE_BRANCH_DES';
export const ALL_CIRCUIT_SORT_BY_VENDOR_ASC = 'ALL_CIRCUIT_SORT_BY_VENDOR_ASC';
export const ALL_CIRCUIT_SORT_BY_VENDOR_DES = 'ALL_CIRCUIT_SORT_BY_VENDOR_DES';
//=============
export const ALL_CIRCUIT_FILTER_BY_LOCATION_ID =
  'ALL_CIRCUIT_FILTER_BY_LOCATION_ID';
export const ALL_CIRCUIT_FILTER_BY_CIRCUITS_ID =
  'ALL_CIRCUIT_FILTER_BY_CIRCUITS_ID';
export const ALL_CIRCUIT_FILTER_BY_BRANCH_ID =
  'ALL_CIRCUIT_FILTER_BY_BRANCH_ID';
export const ALL_CIRCUIT_SORT_BY_STATUS = 'ALL_CIRCUIT_SORT_BY_STATUS';
export const ALL_CIRCUIT_FILTER_BY_STATUS = 'ALL_CIRCUIT_FILTER_BY_STATUS';
export const ALL_CIRCUIT_FILTER_BY_VENDOR = 'ALL_CIRCUIT_FILTER_BY_VENDOR';
export const ALL_CIRCUIT_FILTER_BY_SUBTYPE = 'ALL_CIRCUIT_FILTER_BY_SUBTYPE';
export const ALL_CIRCUIT_FILTER_BY_TYPE = 'ALL_CIRCUIT_FILTER_BY_TYPE';

//============== only data
export const ALL_CIRCUIT_ONLY_VENDOR = 'ALL_CIRCUIT_ONLY_VENDOR';
export const ALL_CIRCUIT_ONLY_TYPE = 'ALL_CIRCUIT_ONLY_TYPE';
export const ALL_CIRCUIT_ONLY_SUBTYPE = 'ALL_CIRCUIT_ONLY_SUBTYPE';
export const ALL_CIRCUIT_ONLY_CIRCUITID = 'ALL_CIRCUIT_ONLY_CIRCUITID';
//==============
export const ALL_CIRCUIT_SEARCH_ONLY_VENDOR = 'ALL_CIRCUIT_SEARCH_ONLY_VENDOR';
export const ALL_CIRCUIT_SEARCH_ONLY_SUBTYPE =
  'ALL_CIRCUIT_SEARCH_ONLY_SUBTYPE';
//==============
export const ALL_DATA = 'ALL_DATA';

//==============
