export const SITE_STATUS_COORDINATES = 'SITE_STATUS_COORDINATES';
export const SEARCH_BY_SITE_ID = 'SEARCH_BY_SITE_ID';
export const SEARCH_BY_BRANCH_ID = 'SEARCH_BY_BRANCH_ID';
//==============FILTER
export const FILTER_BY_ACTIVE = 'FILTER_BY_ACTIVE';
export const FILTER_BY_INACTIVE = 'FILTER_BY_INACTIVE';
export const FILTER_BY_ALL = 'FILTER_BY_ALL';
