export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const SORT_BY_ORDER_ID_ASC = 'SORT_BY_ORDER_ID_ASC';
export const SORT_BY_ORDER_ID_DES = 'SORT_BY_ORDER_ID_DES';
export const SORT_BY_ORDER_TYPE_ASC = 'SORT_BY_ORDER_NAME_ASC';
export const SORT_BY_ORDER_TYPE_DES = 'SORT_BY_ORDER_NAME_DES';
export const SORT_BY_ORDER_STATUS_ASC = 'SORT_BY_ORDER_STATUS_ASC';
export const SORT_BY_ORDER_STATUS_DES = 'SORT_BY_ORDER_STATUS_DES';
export const SORT_BY_ORDER_VENDOR_ASC = 'SORT_BY_ORDER_VENDOR_ASC';
export const SORT_BY_ORDER_VENDOR_DES = 'SORT_BY_ORDER_VENDOR_DES';
//FIETER
export const FILTER_BY_STATUS_ACTIVE = 'FILTER_BY_STATUS_ACTIVE';
export const ALL_DATA = 'ALL_DATA';
