export const GET_ALL_CIRCUIT_INVENTORY = 'GET_ALL_CIRCUIT_INVENTORY';
export const SORT_BY_VENDOR_ASC = 'SORT_BY_VENDOR_ASC';
export const SORT_BY_VENDOR_DES = 'SORT_BY_VENDOR_DES';
export const SORT_BY_CATEGORY_ASC = 'SORT_BY_CATEGORY_ASC';
export const SORT_BY_CATEGORY_DES = 'SORT_BY_CATEGORY_DES';
export const SORT_BY_CIRCUIT_ID_ASC = 'SORT_BY_CIRCUIT_ID_ASC';
export const SORT_BY_CIRCUIT_ID_DES = 'SORT_BY_CIRCUIT_ID_DES';
export const SORT_BY_SUBCAT_1_ASC = 'SORT_BY_SUBCAT_1_ASC';
export const SORT_BY_SUBCAT_1_DES = 'SORT_BY_SUBCAT_1_DES';
//===
export const ALL_DATA = 'ALL_DATA';
//===
export const FILTER_BY_STATUS_ACTIVE = 'FILTER_BY_STATUS_ACTIVE';
