export const GET_ALL_DEVICES_INVENTORY = 'GET_ALL_DEVICES_INVENTORY';
export const SORT_BY_DEVICE_ID_ASC = 'SORT_BY_DEVICE_ID_ASC';
export const SORT_BY_DEVICE_ID_DES = 'SORT_BY_DEVICE_ID_DES';
export const SORT_BY_DEVICE_NAME_ASC = 'SORT_BY_DEVICE_NAME_ASC';
export const SORT_BY_DEVICE_NAME_DES = 'SORT_BY_DEVICE_NAME_DES';
export const SORT_BY_DEVICE_STATUS_ASC = 'SORT_BY_DEVICE_STATUS_ASC';
export const SORT_BY_DEVICE_STATUS_DES = 'SORT_BY_DEVICE_STATUS_DES';
export const SORT_BY_DEVICE_VENDOR_ASC = 'SORT_BY_DEVICE_VENDOR_ASC';
export const SORT_BY_DEVICE_VENDOR_DES = 'SORT_BY_DEVICE_VENDOR_DES';
/// filter
export const FILTER_BY_STATUS_ACTIVE = 'FILTER_BY_STATUS_ACTIVE';
export const ALL_DATA = 'ALL_DATA';
