export const ALL_DEVICES = 'ALL_DEVICE';
export const ALL_DEVICES_DETAILS = 'ALL_DEVICES_DETAILS';
export const ALL_DEVICES_SORT_BY_ID_ASC = 'ALL_DEVICES_SORT_BY_DEVICE_ID_ASC';
export const ALL_DEVICES_SORT_BY_ID_DES = 'ALL_DEVICES_SORT_BY_DEVICE_ID_DES';
export const ALL_DEVICES_SORT_BY_TYPE_ASC =
  'ALL_DEVICES_SORT_BY_DEVICE_NAME_ASC';
export const ALL_DEVICES_SORT_BY_TYPE_DES =
  'ALL_DEVICES_SORT_BY_DEVICE_NAME_DES';
export const ALL_DEVICES_SORT_BY_STATUS_ASC =
  'ALL_DEVICES_SORT_BY_DEVICE_STATUS_ASC';
export const ALL_DEVICES_SORT_BY_STATUS_DES =
  'ALL_DEVICES_SORT_BY_DEVICE_STATUS_DES';
export const ALL_DEVICES_SORT_BY_VENDOR_ASC =
  'ALL_DEVICES_SORT_BY_DEVICE_VENDOR_ASC';
export const ALL_DEVICES_SORT_BY_VENDOR_DES =
  'ALL_DEVICES_SORT_BY_DEVICE_VENDOR_NAME';
export const ALL_DEVICES_SEARCH_BY_VENDOR_NAME =
  'ALL_DEVICES_SEARCH_BY_VENDOR_NAME';
export const ALL_DEVICES_FILTER_BY_VENDOR_NAME =
  'ALL_DEVICES_FILTER_BY_VENDOR_NAME';
export const ALL_DEVICES_SEARCH_BY_DEVICE_TYPE =
  'ALL_DEVICES_SEARCH_BY_DEVICE_TYPE';
export const ALL_DEVICES_FILTER_BY_DEVICE_TYPE =
  'ALL_DEVICES_FILTER_BY_DEVICE_TYPE';
export const ALL_DEVICES_SEARCH_BY_DEVICE_VENDOR =
  'ALL_DEVICES_SEARCH_BY_DEVICE_VENDOR';
export const ALL_DEVICES_FILTER_BY_DEVICE_VENDOR =
  'ALL_DEVICES_FILTER_BY_DEVICE_VENDOR';
export const GET_DEVICES_ONLY_NAME = 'GET_DEVICES_ONLY_NAME';
export const GET_DEVICES_ONLY_TYPE = 'GET_DEVICES_ONLY_TYPE';
export const GET_DEVICES_ONLY_VENDORE = 'GET_DEVICES_ONLY_VENDORE';

//SORT
export const GET_DEVICES_SORT_ACTIVE = 'GET_DEVICES_SORT_ACTIVE';
export const GET_DEVICES_SORT_INACTIVE = 'GET_DEVICES_SORT_INACTIVE';
//==
export const ALL_DATA = 'ALL_DATA';
